spring:
  batch:
    job:
      names: ${job.names:chunkTestJob}
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 10
  profiles:
    active: local
logging:
  level:
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: debug
    jdbc.sqlonly: debug
    org:
      hibernate:
        engine:
          jdbc:
            batch:
              internal:
                BatchingBatch: trace

