openapi: 3.0.1
info:
  title: Test API
  description: My API description
  version: 0.1.0
servers:
- url: https://localhost:8080
tags: []
paths:
  /check:
    get:
      tags:
      - check
      summary: check
      description: check
      operationId: home-check
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/check1496134930'
              examples:
                home-check:
                  value: "{\"ok\":\"ok\"}"
components:
  schemas:
    check1496134930:
      type: object
      properties:
        ok:
          type: string
          description: ok
